stages:
  data_ingestion:
    cmd: python3 src/data/data_ingestion.py
    deps:
    - src/data/data_ingestion.py
    outs:
    - data/interim
  data_preprocessing:
    cmd: python3 src/data/data_preprocessing.py
    deps:
    - data/interim
    - src/data/data_preprocessing.py
    outs:
    - data/processed
  build_features:
    cmd: python3 src/features/build_features.py
    deps:
    - data/processed
    - src/features/build_features.py
    outs:
    - data/features
  train_model:
    cmd: python3 src/models/train_model.py
    deps:
    - data/features
    - src/models/train_model.py
    outs:
    - model.pkl
  predict_model:
    cmd: python3 src/models/predict_model.py
    deps:
    - model.pkl
    - src/models/predict_model.py
    metrics:
    - metrics.json
